### ISSUE TITLE
How ntrip sets the sampling interval for collecting RTCM data streams？

### ISSUE THREAD

**Issue by fenggolang** [go-gnss/ntrip#13]
I want to set the 2-second interval through the ntrip parameter

**Comment by umeat** [comment]
Could you please explain your question a little further? The sample rate is determined by the publisher of the data.

**Comment by fenggolang** [comment]
> Could you please explain your question a little further? The sample rate is determined by the publisher of the data.

for example,rtklib strsvr.exe ntrip options,can set sample rate:
![image](https://user-images.githubusercontent.com/16982786/156382479-4fcf5c0b-f023-470b-8c6a-63160b08a2b3.png)

**Comment by umeat** [comment]
What does that setting actually do? The options shown in the screenshot appear to be general settings, not specifically related to the NTRIP client (you can click "..." in the "opt" column next to the NTRIP client dropdown for specific settings).

Setting the sample rate as the client is not part of the NTRIP protocol.
