### ISSUE TITLE
Server don't support NTRIP V1?

### ISSUE THREAD

**Issue by pyrog** [go-gnss/ntrip#6]
```
go run relay.go -source http://localhost:2101/TEST -dest http://BKG_CASTER:2101/MOUNTPOINT
```
The destination [NTRIP BKG Caster/2.0.37](https://igs.bkg.bund.de/ntrip/bkgcaster) **refuse** the HTTP connexion.

Example of accepted connection by a BKG caster
```
/usr/local/bin/str2str -in ntrip://localhost:2101/TEST -out ntrips://BKG_CASTER:2101/MOUNTPOINT
```

**Note**:
- The source and destination user and password are removed in all these examples for better reading.
- `str` usage: see [RTKLIB ver. 2.4.1 Manual](http://www.rtklib.com/prog/manual_2.4.1.pdf)

**Comment by umeat** [comment]
That's correct - the relay application uses NTRIP v2 for the client and the server.

I will likely not have the time to update the relay application to support v1 as well, but PRs are welcome.

**Comment by pyrog** [comment]
Thank you.

It seem that str2str should support NTRIP V2.0 protocol 😄 
https://github.com/tomojitakasu/RTKLIB/issues/592
